install: true

language: java

jdk: oraclejdk8

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'

script :
 - cd fr.lip6.move.gal.itscl.parent 
 - mvn clean generate-sources install
 - cd ..
 - cp fr.lip6.move.gal.itscl.product/target/products/*.zip website/
 - cd website
 - zip -d fr.lip6.move.gal.itscl.product-linux.gtk.x86_64.zip '*its-*-win64' '*its-*-linux32' '*its-*-Darwin'
 - zip -d fr.lip6.move.gal.itscl.product-macosx.cocoa.x86_64.zip '*its-*-win64' '*its-*-linux32' '*its-*-linux64'
 - zip -d fr.lip6.move.gal.itscl.product-win32.win32.x86_64.zip '*its-*-linux64' '*its-*-linux32' '*its-*-Darwin'
 - cd ..
 - ls -lah website/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  on:
    branch: master
   

